name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js (for React build)
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Or whichever version you prefer

      - name: Install dependencies (React)
        run: |
          npm install       # No need for 'cd', since React is at root level

      - name: Build React app
        run: |
          npm run build     # Builds the React app (output in build/ folder)

      - name: Setup Pages for Jekyll
        uses: actions/configure-pages@v5

      - name: Build Jekyll site
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Copy React build to _site directory
        run: |
          cp -R build/* ./_site/  # Copy React build files to Jekyll _site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
